\# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=9.1'
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=10.0'
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=9.1'
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=10.0'

#cache: cocoapods
#podfile: Example/Podfile
before_install:
  - gem install cocoapods --pre # Since Travis is not always on latest version
#- pod install --project-directory=Example

script:
- set -o pipefail
- xcodebuild test -destination "$DESTINATION" -workspace Example/NSURLSession-Mock.xcworkspace -scheme NSURLSession-Mock-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
